services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-film-db
    environment:
      MYSQL_DATABASE: filmdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - filmdb-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  app:
    build: .
    container_name: spring-film-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/filmdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - OMDB_API_KEY=YOUR_API_KEY
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  filmdb-data: